import {
  Page,
  Heading,
  Paragraph,
  Link,
  Card,
  Alert,
  Button,
  Table,
  List,
  ListItem,
  Stat,
  Progress,
  Descriptions,
  CodeSpan,
} from "@readable-ui/react/components";
import { definePage } from "@readable-ui/react";
import { adminNav } from "../_shared/admin-nav";

interface WeeklyMetric extends Record<string, unknown> {
  id: string;
  week: string;
  signups: number;
  active: number;
  revenue: string;
}

interface TopPlan extends Record<string, unknown> {
  id: string;
  plan: string;
  customers: number;
  mrr: string;
  growth: string;
}

const weekly: WeeklyMetric[] = [
  { id: "w2026-16", week: "2026-W16", signups: 142, active: 894, revenue: "$28,430" },
  { id: "w2026-15", week: "2026-W15", signups: 128, active: 871, revenue: "$26,110" },
  { id: "w2026-14", week: "2026-W14", signups: 119, active: 842, revenue: "$24,980" },
  { id: "w2026-13", week: "2026-W13", signups: 106, active: 817, revenue: "$23,410" },
];

const topPlans: TopPlan[] = [
  { id: "plan_team", plan: "Team", customers: 214, mrr: "$12,840", growth: "+8.1%" },
  { id: "plan_pro", plan: "Pro", customers: 486, mrr: "$9,720", growth: "+3.4%" },
  { id: "plan_starter", plan: "Starter", customers: 1102, mrr: "$5,510", growth: "+1.2%" },
];

export const reportsPage = definePage({
  envelope: {
  title: "Reports",
  purpose:
    "Business reporting — weekly KPI snapshot, plan-level revenue split, and exportable drill-downs.",
  role: "admin",
  layout: "topbar",
  nav: { items: adminNav.active("/reports") },
  // ADR 0024 §4: breadcrumb showcases hierarchical path in a topbar layout.
  breadcrumb: [
    { label: "Home", href: "/" },
    { label: "Reports" },
  ],
  paths: {
    view: "/reports",
    markdown: "/reports.md",
  },
  updatedAt: "2026-04-18T06:00:00Z",
  constraints: [
    {
      id: "cohort-utc",
      severity: "info",
      text: "All cohorts are grouped in UTC. Local-time slicing is not yet supported.",
    },
    {
      id: "revenue-accrual",
      severity: "warn",
      text: "Revenue is accrual-based. It may differ from billed totals by up to 48 hours.",
    },
  ],
  tools: [
    {
      name: "exportReport",
      title: "Export report",
      description: "Export the current report to CSV.",
      role: "admin",
      input: {
        type: "object",
        properties: {
          scope: { type: "string", enum: ["weekly", "plans"] },
        },
        required: ["scope"],
      },
    },
    {
      name: "viewPlan",
      title: "View plan detail",
      description: "Open a subscription plan detail view.",
      role: "admin",
      input: {
        type: "object",
        properties: { id: { type: "string" } },
        required: ["id"],
      },
    },
    {
      name: "openWeek",
      title: "Open weekly cohort",
      description: "Open a weekly cohort drill-down view.",
      role: "admin",
      input: {
        type: "object",
        properties: { id: { type: "string" } },
        required: ["id"],
      },
    },
  ],
  },
  render: () => (
    <Page>
      <Heading level={1}>Reports</Heading>
      <Paragraph>
        Weekly business snapshot for the Acme admin workspace. Compare with the{" "}
        <Link href="/reports.md">Markdown view</Link> to see the same data AI-ready.
      </Paragraph>

      <Alert kind="tip">
        Week 16 is still in progress — numbers update every hour at :05.
      </Alert>

      {/* ADR 0024 §1: KPI cards replaced with Stat directive. */}
      <Stat label="Revenue (WoW)" value="$28,430" delta="+8.9%" trend="up" unit="week 16" />
      <Stat label="Signups · 7d" value="142" delta="+10.9%" trend="up" />
      <Stat label="Active accounts · 48h" value="894" delta="+2.6%" trend="up" />
      <Stat label="Churn · 7d" value="23" delta="-3.2%" trend="down" />

      {/* ADR 0024 §2: Progress variants against quota. */}
      <Card title="Quota usage">
        <Progress value={720} max={1000} label="API calls" variant="primary" />
        <Progress value={42} max={50} label="Active workspaces" variant="success" />
        <Progress value={88} max={100} label="Storage (GB)" variant="warning" />
        <Progress value={98} max={100} label="Seats" variant="danger" />
      </Card>

      {/* ADR 0024 §3: Descriptions convenience — renders as Card + List per ADR 0018. */}
      <Descriptions
        title="Report metadata"
        items={[
          { term: "Period", value: "2026-W13 \u2013 2026-W16" },
          { term: "Timezone", value: <CodeSpan>UTC</CodeSpan> },
          { term: "Generated by", value: "weekly-kpi-job" },
          { term: "Comparison baseline", value: "2026-W12" },
          { term: "Owner", value: null },
        ]}
      />

      <Card title="Retention notes">
        <List>
          <ListItem>Week-1 retention is steady at 64% across plans.</ListItem>
          <ListItem>Team plan expansion driven by seat top-ups, not new logos.</ListItem>
          <ListItem>Churn concentrated in Starter plan — investigate onboarding funnel.</ListItem>
        </List>
      </Card>

      <Table<WeeklyMetric>
        caption="Weekly KPI snapshot"
        columns={[
          { key: "week", label: "Week" },
          { key: "signups", label: "Signups", align: "right" },
          { key: "active", label: "Active", align: "right" },
          { key: "revenue", label: "Revenue", align: "right" },
        ]}
        rows={weekly}
        actions={[
          {
            tool: "openWeek",
            label: "Open",
            params: (r) => ({ id: r.id }),
          },
        ]}
      />

      <Table<TopPlan>
        caption="Revenue by plan"
        columns={[
          { key: "plan", label: "Plan" },
          { key: "customers", label: "Customers", align: "right" },
          { key: "mrr", label: "MRR", align: "right" },
          { key: "growth", label: "Growth", align: "right" },
        ]}
        rows={topPlans}
        actions={[
          {
            tool: "viewPlan",
            label: "Details",
            params: (r) => ({ id: r.id }),
          },
        ]}
      />

      <Card title="Export">
        <Paragraph>
          Snapshot the current view for sharing. Exports are delivered as CSV via email.
        </Paragraph>
        <Button action="exportReport">Export weekly CSV</Button>
      </Card>
    </Page>
  ),
});
